params:
  comments: true
  homeInfoParams:
    Title: Welcome Friends!
    Content: Per Aspera Ad Astra!
  socialIcons:
    - name: GitHub
      url: https://github.com/Lg-Cr
    - name: CodeForces
      url: https://codeforces.com/profile/lightcreeper
menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/posts/about/"
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"