params:
  show_categories_on_home: true
  show_tags_on_home: true
  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  VisitCount: true
  ShowWordCount: true
  math: true

  homeInfoParams:
    Title: Welcome Friends!
    Content: Per Aspera Ad Astra!
  socialIcons:
    - name: GitHub
      url: https://github.com/Lg-Cr
    - name: CodeForces
      url: https://codeforces.com/profile/lightcreeper
menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/posts/about/"
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
    - identifier: "search"
      name: "Search"
      url: "/search/"
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true