params:
  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  VisitCount: true
  ShowWordCount: true
  homeInfoParams:
    Title: Welcome Friends!
    Content: Per Aspera Ad Astra!
  socialIcons:
    - name: GitHub
      url: https://github.com/Lg-Cr
    - name: CodeForces
      url: https://codeforces.com/profile/lightcreeper
menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/posts/about/"
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
    - identifier: "search"
      name: "Search"
      url: "/search/"
outputs:
  home:
    - HTML
    - RSS
    - JSON