# config.yaml
baseURL: "https://inftress.pages.dev/"   # 换成你自己的
languageCode: "zh-cn"
title: "Inftopia"
theme: "PaperMod"

# 启用代码高亮
markup:
  goldmark:
    renderer:
      unsafe: true   # 允许渲染HTML（KaTeX 需要）
  highlight:
    noClasses: false
    style: "monokai"   # 代码高亮主题

# 菜单
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 100

# PaperMod 主题参数
params:
  author: "Inftress"
  defaultTheme: auto   # 自动切换明暗主题
  ShowCodeCopyButtons: true   # 显示代码复制按钮
  ShowReadingTime: true
  ShowToc: true
  hasCJKLanguage: true
  homeInfoParams:
    Title: "Inftress"
    Content: "The end of this world, and the girl who crossed the sea."
  utterances:
    enable: true
    repo: "lg-cr/blog-comments"
    issueTerm: "pathname"   # 按路径名关联 Issue
    theme: "github-dark"
  socialIcons:
    - name: "Github"
      url: "https://github.com/Lg-Cr"
    - name: "Codeforces"
      url: "https://codeforces.com/profile/Infter"


outputs:
  home:
    - HTML
    - RSS
    - JSON